version: "3"
services:
    mydb:
        container_name: mydbb
        image: mysql:5.7
        ports:
            - "32001:3306"
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_USER: "massba"
            MYSQL_PASSWORD: "root"
            MYSQL_DATABASE: "mydb"
            
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10
        
    app:
        container_name: myapp
        image: myapp
        ports:
            - "8081:8080"
        depends_on:
          mydb:
            condition: service_healthy
        links: 
            - mydb

  